# Site settings
title: Alejandro Magallanes
header-img: img/home-bg.jpg
email: alejandromagallanesd@gmail.com
copyright_name: Procrastes Press
description: "The dreamer"
baseurl: ""
url: "https://am941573.github.io/website2/"
twitter_username: magallanesalej
github_username:  
facebook_username: magallanesalej
email_username:  alejandromagallanesd@gmail.com
linkedin_username: magallanesalej
phone_number: "1-806-676-5366"
map_address: "2300 N. Western, Amarillo, TX 79124"

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
#google_tracking_id: UA-1601268-12

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
